import { z } from "zod";
import { createUserScopedSupabaseClient } from "../lib/supabase.js";
import type { NotificationListQuery, NotificationPreferencesInput } from "../schemas/notifications.js";

const notificationRow = z.object({ id:z.uuid(),type:z.string(),category:z.string(),title:z.string(),body:z.string(),resource_type:z.string().nullable(),resource_id:z.uuid().nullable(),created_at:z.string(),read_at:z.string().nullable() });
const preferenceRow = z.object({ profile_in_app:z.boolean(),profile_email:z.boolean(),contact_in_app:z.boolean(),contact_email:z.boolean(),verification_in_app:z.boolean(),verification_email:z.boolean() });
export class NotificationServiceError extends Error { constructor(public readonly code:"NOTIFICATION_NOT_FOUND"|"NOTIFICATION_FAILED"){super(code);this.name="NotificationServiceError";} }
export const defaultPreferences = { profile:{inApp:true,email:true},contact:{inApp:true,email:true},verification:{inApp:true,email:true} };

export const listNotifications=async(token:string,q:NotificationListQuery)=>{let query=createUserScopedSupabaseClient(token).from("notifications").select("id,type,category,title,body,resource_type,resource_id,created_at,read_at").order("created_at",{ascending:false}).order("id",{ascending:false}).range(q.offset,q.offset+q.limit);if(q.unreadOnly)query=query.is("read_at",null);const{data,error}=await query;if(error)throw new NotificationServiceError("NOTIFICATION_FAILED");const p=z.array(notificationRow).safeParse(data??[]);if(!p.success)throw new NotificationServiceError("NOTIFICATION_FAILED");const hasMore=p.data.length>q.limit;return{notifications:p.data.slice(0,q.limit).map(n=>({id:n.id,type:n.type,category:n.category,title:n.title,body:n.body,resourceType:n.resource_type,resourceId:n.resource_id,createdAt:n.created_at,readAt:n.read_at})),pageInfo:{limit:q.limit,offset:q.offset,hasMore}};};
export const markNotificationRead=async(token:string,id:string)=>{const{error}=await createUserScopedSupabaseClient(token).rpc("mark_notification_read",{p_notification_id:id});if(error){if(error.code==="P0002")throw new NotificationServiceError("NOTIFICATION_NOT_FOUND");throw new NotificationServiceError("NOTIFICATION_FAILED");}return{success:true};};
export const markAllNotificationsRead=async(token:string)=>{const{data,error}=await createUserScopedSupabaseClient(token).rpc("mark_all_notifications_read");if(error)throw new NotificationServiceError("NOTIFICATION_FAILED");return{updatedCount:typeof data==="number"?data:0};};
export const getNotificationPreferences=async(token:string)=>{const{data,error}=await createUserScopedSupabaseClient(token).from("notification_preferences").select("profile_in_app,profile_email,contact_in_app,contact_email,verification_in_app,verification_email").maybeSingle();if(error)throw new NotificationServiceError("NOTIFICATION_FAILED");if(!data)return defaultPreferences;const p=preferenceRow.safeParse(data);if(!p.success)throw new NotificationServiceError("NOTIFICATION_FAILED");return{profile:{inApp:p.data.profile_in_app,email:p.data.profile_email},contact:{inApp:p.data.contact_in_app,email:p.data.contact_email},verification:{inApp:p.data.verification_in_app,email:p.data.verification_email}};};
export const putNotificationPreferences=async(token:string,p:NotificationPreferencesInput)=>{const{error}=await createUserScopedSupabaseClient(token).rpc("upsert_notification_preferences",{p_profile_in_app:p.profile.inApp,p_profile_email:p.profile.email,p_contact_in_app:p.contact.inApp,p_contact_email:p.contact.email,p_verification_in_app:p.verification.inApp,p_verification_email:p.verification.email});if(error)throw new NotificationServiceError("NOTIFICATION_FAILED");return p;};
